### ISSUE TITLE
Latest content validation causes deserialize failure due to sequence instead of string

### ISSUE THREAD

**Issue by kdeme** [ethereum/glados#103]
Error seen when running local glados instance, due to validation addition in #99.

```
[2023-04-07T08:52:31Z WARN  glados_audit::validation] could not deserialize content bytes content.value="0x080000001b020000f9021..." err=Error("invalid type: sequence, expected a string", line: 0, column: 0)
```

At first glance, it seems to be rather an issue in what is expected as JSON data here: https://github.com/ethereum/glados/blob/master/glados-audit/src/validation.rs#L10.

I might be wrong as I don't really know this code base but I think the data coming from `get_content` (https://github.com/ethereum/glados/blob/master/glados-audit/src/lib.rs) is just the raw SSZ encoded bytes, and thus likely not to be accepted by the JSON parsing in the validation code?

**Comment by perama-v** [comment]
It does look like the source is as you say, ~L10 in validation.rs

`serde_json::from_value()` should be replaced with `decode()`, from here https://github.com/ethereum/trin/blob/master/trin-types/src/content_value.rs#L130

Like this: https://github.com/ethereum/trin/blob/master/trin-types/src/content_value.rs#L254

**Comment by kdeme** [comment]
Thanks, that works:

```
diff --git a/glados-audit/src/validation.rs b/glados-audit/src/validation.rs
index 55d0088..9415824 100644
--- a/glados-audit/src/validation.rs
+++ b/glados-audit/src/validation.rs
@@ -1,4 +1,4 @@
-use ethportal_api::{BlockHeaderKey, HistoryContentKey, HistoryContentValue, OverlayContentKey};
+use ethportal_api::{BlockHeaderKey, HistoryContentKey, HistoryContentValue, OverlayContentKey, ContentValue};
 use tracing::warn;
 use trin_utils::bytes::hex_encode;
 
@@ -6,8 +6,8 @@ use trin_utils::bytes::hex_encode;
 /// content value.
 pub fn content_is_valid(content_key: &HistoryContentKey, content_bytes: &[u8]) -> bool {
     // check deserialization is valid
-    let content: HistoryContentValue = match serde_json::from_value::<HistoryContentValue>(
-        content_bytes.into(),
+    let content: HistoryContentValue = match HistoryContentValue::decode(
+        content_bytes,
     ) {
         Ok(c) => c,
         Err(e) => {
```

**Comment by kdeme** [comment]
fixed in https://github.com/ethereum/glados/pull/104
