### ISSUE TITLE
Web view for DHT census data

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/glados#163]
We should have a web view to explore census data.

- Paginated list of all past census data showing (Id/CreatedAt/NumNodes)
- Detail page for a census that shows meta stats (CreatedAt/NumNodes), client diversity graph, and a list of all found ENR records

**Comment by KolbyML** [comment]
I am going to pick this up, as Piper said it is a good thing to have before the feature I want. I believe Mike is focused on other area's right now and this issue should be very quick. I feel a little weird taking over a issue someone self assigned themselves to so hopefully it is alright, mike ping me if you are almost done or wanted to do this.
