### ISSUE TITLE
glados-web unavailable due to panicks

### ISSUE THREAD

**Issue by kdeme** [ethereum/glados#205]
Getting this error on glados-web when running it manually in combination with glados-audit, glados-monitor and glados-cartographer. Tried both with existing sqlite db and with a fresh sqlite db.

```
[2023-12-01T12:48:10Z DEBUG hyper::proto::h1::io] parsed 12 headers
[2023-12-01T12:48:10Z DEBUG hyper::proto::h1::conn] incoming body is empty
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Type("A null value was encountered while decoding \"id\"")', /home/deme/repos/glados/glados-web/src/routes.rs:206:10
[2023-12-01T12:48:10Z INFO  sqlx::query] SELECT MAX("id") AS "id" …; rows affected: 1, rows returned: 1, elapsed: 34.105µs
    
    SELECT
      MAX("id") AS "id"
    FROM
      "census"
```    

The culpit commit appears to be 5702b8a503cb8f52a14c7419e5559170123f3750, before this commit it still works.

**Comment by kdeme** [comment]
According to @KolbyML solution here is to use Postgres instead of sqlite. Sqlite will be removed and basically is already not supported due to this issue.

**Comment by kdeme** [comment]
@KolbyML I think this issue also exists for postgres deployments. I've deleted my postgres db when I was testing with the docker compose solution and suddenly this error hits also.

**Comment by KolbyML** [comment]
Oh ok I will make a PR to fix this 👍
