### ISSUE TITLE
Audit dashboard showing page title as "Content Dashboard"

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/glados#254]
### What is wrong

It seems the "title" of the audit dashboard page is showing in the browser as "Content Dashboard" which is probably just a copy/pasta error in our templates.

https://glados.ethdevops.io/audits/

### How should it be fixed

Make the page show an HTML title of "Audit Dashboard" to match the page.

**Comment by Ktl-XV** [comment]
This issue has already been fixed by #281
