### ISSUE TITLE
Support for running multiple clients for glados-audit

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/glados#88]
With #85 being added, it seems we now will want the ability to run `glados-audit` with multiple clients.

- Change the audit schema to allow storing information about the client that was used for the audit.  I suggest we store both a reference to the `ENR` record and the client version string.
- Change to allow "multiple" clients (requiring at least 1) to be specified via `--ipc-path` or `--http-url`
- Change the audit process to round-robin audits across all of the available clients

**Comment by pipermerriam** [comment]
Ok, I think I know how I want to do this.

first, I'd like to implement the ability to do

- `--portal-client http://127.0.0.1:8545`
- `--portal-client ipc:////path/to/portal_jsonrpc.ipc`

And on the rust side, it would be nice to be able to do something like:

```
HistoryClient::from(portal_client_url)
```

Then we need a small abstraction of some kind to allow us to "pool" multiple client such that we can use them like a connection pool.

**Comment by KolbyML** [comment]
https://github.com/ethereum/glados/pull/110 closes this
