### ISSUE TITLE
Accept `null` as "no content" response

### ISSUE THREAD

**Issue by perama-v** [ethereum/glados#97]
### Description

Glados treats `null` responses from Portal Network node `portal_recursiveFindContentResult` as an error. It should treat these the same as "0x" (interpreted as "content not found")

I had followed some discussion in the following PR (https://github.com/ethereum/portal-network-specs/pull/176), but now I see that this is specifically for `portal_*LocalContent`, which uses a special `"0x0"` response. 

Looking at the spec
```
  "RecursiveFindContentResult": {
    "name": "recursiveFindContentResult",
    "description": "The data corresponding to the lookup target",
    "schema": {
      "title": "Encoded target content data",
      "$ref": "#/components/schemas/hexString"
    }
  },
```
Where hexString is:
```
  "hexString": {
    "title": "Hex string",
    "type": "string",
    "pattern": "^0x[0-9a-f]$"
  }
```

So `null` and `"0x"` both seem valid and Glados should look for these to mean "content is absent". Rather than the current behaviour of looking only for `"0x"`. 

Relevant code:

https://github.com/ethereum/glados/blob/master/glados-core/src/jsonrpc.rs#L166-L186

**Comment by pipermerriam** [comment]
The definition of `hexString` doesn't look to me like it accepts a null value...   It is a `string` type with a regex that specifically requires a `0x` prefix...

**Comment by perama-v** [comment]
Ok I think I agree that `null` is not valid

The [spec](https://github.com/ethereum/portal-network-specs/blob/master/jsonrpc/src/methods/history.json#L91-L105) `portal_recursiveFindContentResult` result field has only the `FindContentResult`.
```json
"result": {
  "$ref": "#/components/contentDescriptors/FindContentResult"
}
```
Were `null` valid it would have:
```json
"result": {
  "oneOf": [
  {
     "$ref": "#/components/contentDescriptors/FindContentResult"
  },
  {
    "$ref": "#/components/schemas/Null"
  }
]
}
```
